# Generated by Django 5.0.3 on 2024-03-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='demo_link',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='projects',
            name='github_link',
            field=models.URLField(default=None),
        ),
    ]
